name: rdm-editable
channels:
  - conda-forge
dependencies:
  - anyio=4.10.0=pyhe01879c_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h3485c13_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hda3d55a_3
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.8.3=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - conda=25.7.0=py311h1ea47a8_0
  - conda-libmamba-solver=25.4.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.1.0=hc790b64_1
  - cpython=3.11.13=py311hd8ed1ab_0
  - debugpy=1.8.16=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fmt=11.2.0=h1d4551f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - frozendict=2.4.6=py311he736701_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.4.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h1ea47a8_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab-myst=2.4.2=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.2.2=pyhd8ed1ab_1
  - libarchive=3.8.1=gpl_h1ca5a36_100
  - libcurl=8.14.1=h88aaa65_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libiconv=1.18=hc1393d2_2
  - liblzma=5.8.1=h2466b09_2
  - libmamba=2.3.1=hd264f3a_1
  - libmambapy=2.3.1=py311ha41deb9_1
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.35=h8883371_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - markupsafe=3.0.2=py311h5082efb_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - menuinst=2.3.1=py311h3e6a449_0
  - mistune=3.1.3=pyh29332c3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.3=he0c23c2_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.5.2=h725018a_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311he736701_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311he736701_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_0
  - pywinpty=2.0.15=py311hda3d55a_0
  - pyyaml=6.0.2=py311h5082efb_2
  - pyzmq=27.0.1=py311ha362a94_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.5.post0=h2466b09_0
  - reproc-cpp=14.2.5.post0=he0c23c2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.0=py311hf51aa87_0
  - ruamel.yaml=0.18.15=py311h3485c13_0
  - ruamel.yaml.clib=0.2.8=py311he736701_1
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=3.13.0=hc790b64_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh5737063_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py311h3485c13_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=h57928b3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - yaml=0.2.5=h6a83c73_3
  - yaml-cpp=0.8.0=he0c23c2_0
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py311he736701_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - about-time==4.2.1
      - addict==2.3.0
      - alive-progress==3.3.0
      - arviz==0.23.1
      - autograd==1.8.0
      - backports-tarfile==1.2.0
      - binaryornot==0.4.4
      - build==1.3.0
      - cadet-process==0.11.1
      - cadet-python==1.1.2
      - cadet-rdm==1.0.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - click==8.2.1
      - cma==4.4.2
      - contourpy==1.3.3
      - cookiecutter==2.6.0
      - corner==2.2.3
      - cryptography==45.0.6
      - cycler==0.12.1
      - deprecated==1.3.1
      - dill==0.4.1
      - diskcache==5.6.3
      - distlib==0.4.0
      - docker==7.1.0
      - filelock==3.19.1
      - flake8==7.3.0
      - fonttools==4.59.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - graphemeu==0.7.2
      - h5netcdf==1.8.1
      - h5py==3.15.1
      - hopsy==1.6.1
      - identify==2.6.13
      - iniconfig==2.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - joblib==1.5.3
      - keyring==25.6.0
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - markdown-it-py==4.0.0
      - matplotlib==3.10.5
      - mccabe==0.7.0
      - mdurl==0.1.2
      - moocore==0.2.0
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multiprocess==0.70.19
      - nodeenv==1.9.1
      - numba==0.63.1
      - numpy==2.3.2
      - optlang==1.8.3
      - pandas==3.0.0
      - pathos==0.3.5
      - pillow==11.3.0
      - polyround==0.4.0
      - pox==0.3.7
      - ppft==1.7.8
      - pre-commit==4.3.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygithub==2.7.0
      - pyjwt==2.10.1
      - pymoo==0.6.1.6
      - pynacl==1.5.0
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pytest==8.4.1
      - python-gitlab==6.2.0
      - python-slugify==8.0.4
      - pywin32-ctypes==0.2.3
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - semantic-version==2.10.0
      - smmap==5.0.2
      - swiglpk==5.0.12
      - sympy==1.14.0
      - tabulate==0.9.0
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tzdata==2025.3
      - virtualenv==20.34.0
      - wrapt==2.1.1
      - xarray==2026.1.0
      - xarray-einstats==0.9.1
prefix: C:\Users\katha\miniforge3\envs\rdm-editable
