name: cadet_dev
channels:
  - conda-forge
dependencies:
  - lazygit
  - pip
  - python=3.12
  - seaborn
  - cadet==5.1.0
  - sphinx-subfigure
  - jupytext
prefix: /home/IBT/lanzrath/miniforge3/envs/cadet_dev
