name: cadet_dev
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _x86_64-microarch-level=3=2_skylake
  - alabaster=1.0.0=pyhd8ed1ab_1
  - babel=2.17.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cadet=5.1.0=hc9d1263_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h68727a3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - fonttools=4.56.0=py312h178313f_0
  - freetype=2.13.3=h48d6fc4_0
  - gmp=6.3.0=hac33072_2
  - hdf5=1.14.6=nompi_h2d575fe_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupytext=1.18.1=pyh80e38bb_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lazygit=0.48.0=h59e48b9_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libamd=3.3.3=haaf9dc3_7100102
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcblas=3.9.0=31_he106b2a_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libcolamd=3.3.4=h32481e8_7100102
  - libcurl=8.14.0=h332b0f4_0
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - libklu=2.3.5=hf24d653_7100102
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libldl=3.3.2=h32481e8_7100102
  - liblzma=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libparu=1.0.0=h17147ab_7100102
  - libpng=1.6.47=h943b412_0
  - librbio=4.3.4=h32481e8_7100102
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libtiff=4.7.0=hd9ff511_3
  - libumfpack=6.3.5=heb53515_7100102
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.7=h0d44e9d_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - metis=5.1.0=hd0bcaf9_1007
  - mpfr=4.2.1=h90cbb55_3
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.1.0=py312h80c1187_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - scipy=1.15.2=py312ha707e6e_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinx-subfigure=0.2.4=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - statsmodels=0.14.4=py312hc0a28a1_0
  - suitesparse=7.10.1=ha0f6916_7100102
  - superlu=7.0.1=h8f6e6c4_0
  - tbb=2022.1.0=h4ce085d_0
  - tbb-devel=2022.1.0=h1f99690_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.3.0=pyhcf101f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_1
  - pip:
      - about-time==4.2.1
      - accessible-pygments==0.0.5
      - addict==2.3.0
      - alive-progress==3.2.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.21.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - autograd==1.7.0
      - ax-platform==0.4.3
      - beautifulsoup4==4.13.3
      - betterproto==2.0.0b6
      - binaryornot==0.4.4
      - bleach==6.2.0
      - botorch==0.12.0
      - build==1.2.2.post1
      - cadet-gui==0.0.0
      - cadet-process==0.11.1
      - cadet-python==1.0.4
      - cadet-rdm==1.0.1
      - cattrs==25.1.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.2.1
      - cma==3.2.2
      - comm==0.2.2
      - cookiecutter==2.6.0
      - corner==2.2.3
      - coverage==7.9.0
      - cryptography==45.0.4
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.9
      - diskcache==5.6.3
      - distlib==0.3.9
      - doc8==2.0.0
      - docker==7.1.0
      - esbonio==0.16.5
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fqdn==1.5.1
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gpytorch==1.13
      - grapheme==0.6.0
      - greenlet==3.2.3
      - grpclib==0.4.7
      - h11==0.14.0
      - h2==4.2.0
      - h5netcdf==1.6.1
      - h5py==3.13.0
      - hagelkorn==1.2.3
      - hopsy==1.6.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - id==1.5.0
      - identify==2.6.9
      - importlib-metadata==8.7.0
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipympl==0.9.7
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jaxtyping==0.2.19
      - jedi==0.19.2
      - jeepney==0.9.0
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-cache==1.0.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keyring==25.6.0
      - latexcodec==3.0.0
      - linear-operator==0.5.3
      - llvmlite==0.44.0
      - lsprotocol==2023.0.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mcbackend==0.5.2
      - mdit-py-plugins==0.4.2
      - mistune==3.1.2
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.2.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.17
      - mypy-extensions==1.0.0
      - myst-nb==1.2.0
      - myst-parser==4.0.1
      - narwhals==1.31.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nh3==0.2.21
      - nodeenv==1.9.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==2.1.3
      - numpydoc==1.8.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optlang==1.8.3
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.3
      - pbr==6.1.1
      - pexpect==4.9.0
      - pip==26.0.1
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pluggy==1.5.0
      - polyround==0.3.0
      - pox==0.3.5
      - ppft==1.7.6.9
      - pre-commit==4.1.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydata-sphinx-theme==0.15.4
      - pygithub==2.6.1
      - pygls==1.3.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pymoo==0.6.1.3
      - pynacl==1.5.0
      - pyproject-hooks==1.2.0
      - pyre-extensions==0.0.32
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pyspellchecker==0.8.3
      - pytest==8.3.5
      - pytest-cov==6.2.0
      - python-gitlab==6.1.0
      - python-json-logger==3.3.0
      - python-slugify==8.0.4
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - readme-renderer==44.0
      - referencing==0.36.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - restructuredtext-lint==1.4.0
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.23.1
      - rstcheck==6.2.5
      - rstcheck-core==1.2.2
      - ruff==0.11.4
      - scikit-learn==1.6.1
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sphinx-book-theme==1.1.4
      - sphinx-copybutton==0.5.2
      - sphinx-multiversion==0.2.4
      - sphinx-sitemap==2.6.0
      - sphinxcontrib-bibtex==2.6.3
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.41
      - stack-data==0.6.3
      - stevedore==5.4.1
      - swiglpk==5.0.12
      - sympy==1.13.1
      - tabulate==0.9.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - triton==3.2.0
      - twine==6.1.0
      - typeguard==4.4.4
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - virtualenv==20.29.3
      - wadler-lindig==0.1.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xarray==2025.1.2
      - xarray-einstats==0.8.0
      - yuml==0.2
      - zipp==3.23.0
prefix: /home/IBT/lanzrath/miniforge3/envs/cadet_dev
